### ISSUE TITLE
I don't think the lib should require env vars

### ISSUE THREAD

**Issue by smeriwether** [wearemolecule/kubeclient#5]
I don't like how the library requires env vars to use. Every time I use the library I forget what env vars are needed (they aren't documented anywhere) and it takes a few minutes to get back on track. I also just don't think a library should have hidden dependencies. 

It currently requires 3 env vars:
- CERTS_PATH
- KUBERNETES_SERVICE_HOST
- KUBERNETES_SERVICE_PORT

I think we should have those 3 vars passed into the `GetKubeClientFromEnv()` method.

**Comment by smeriwether** [comment]
@iterion what do you think?

**Comment by iterion** [comment]
Yeah, agree, config should just be passed in. A lot of times you see a `Config` struct that gets passed in as well. That might be more flexible for future additions/changes. 

Also, on the cluster we should be able to use the certs that are already present instead of needing to make a secret each time we want to interact with the kube master.

Kubeclient should probably provide helpers to get config vars from different sources and set up a config struct. This would make the API clearer. If we do this we should also rename `GetKubeClientFromEnv()` to maybe just `New(config)`

Config stuff might be in its own subpackage. So, there the api might be like `config.FromEnv()`.
